      #pages
app :
      path: /application
      controller: Home::app
      hash:
        vasya : masya::res
        asya : pasya::res
home :
      path : /
      controller : Home::home
      hash :
        and : twohash
        and2 : tree
